config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :adocaos
  resources :adotantes
  resources :website
  get 'website/adoption'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "website#index"
end

app/models/adotante.rb
class Adotante < ApplicationRecord
  validates_presence_of :nome, :estado, :marcou_comprometimento
  validates :email,
            format: { with: /\A\S+@.+\.\S+\z/, message: ": favor informar um e-mail válido"  },
            uniqueness: { case_sensitive: false },
            length: { minimum: 6, maximum: 254 }
  has_many :adocaos
  has_many :pnas, :through => :adocao

  def adotar(povo_filho)
    ENV["TZ"] ||= "America/Sao_Paulo" 
    adocao = nil
    unless povo_filho.nil?
      adocao = Adocao.new
      adocao.adotante = self
      adocao.pna = povo_filho
      adocao.data_adocao = Time.now
      adocao.save
    end
  end
end

app/controllers/adotantes_controller.rb
class AdotantesController < ApplicationController
  before_action :set_adotante, only: [:show, :edit, :update, :destroy]

  # GET /adotantes
  # GET /adotantes.json
  def index
    @adotantes = Adotante.all
  end

  # GET /adotantes/1
  # GET /adotantes/1.json
  def show
  end

  # GET /adotantes/new
  def new
    @adotante = Adotante.new
  end

  # GET /adotantes/1/edit
  def edit
  end

  # POST /adotantes
  # POST /adotantes.json
  def create
    @adotante = Adotante.new(adotante_params)

    respond_to do |format|
      if @adotante.save
        format.html { redirect_to @adotante, notice: 'Adotante was successfully created.' }
        format.json { render :show, status: :created, location: @adotante }
      else
        format.html { render :new }
        format.json { render json: @adotante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adotantes/1
  # PATCH/PUT /adotantes/1.json
  def update
    respond_to do |format|
      if @adotante.update(adotante_params)
        format.html { redirect_to @adotante, notice: 'Adotante was successfully updated.' }
        format.json { render :show, status: :ok, location: @adotante }
      else
        format.html { render :edit }
        format.json { render json: @adotante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adotantes/1
  # DELETE /adotantes/1.json
  def destroy
    @adotante.destroy
    respond_to do |format|
      format.html { redirect_to adotantes_url, notice: 'Adotante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adotante
      @adotante = Adotante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adotante_params
      params.require(:adotante).permit(:nome, :estado, :email, :telefone, :pedido_oracao, :marcou_comprometimento)
    end
end

app/helpers/adotantes_helper.rb
module AdotantesHelper
end

app/views/adotantes/_form.html.erb
<%= form_with(model: adotante, local: true) do |form| %>
  <% if adotante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adotante.errors.count, "error") %> prohibited this adotante from being saved:</h2>

      <ul>
        <% adotante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :pedido_oracao %>
    <%= form.text_area :pedido_oracao %>
  </div>

  <div class="field">
    <%= form.label :marcou_comprometimento %>
    <%= form.check_box :marcou_comprometimento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adotantes/edit.html.erb
<h1>Editing Adotante</h1>

<%= render 'form', adotante: @adotante %>

<%= link_to 'Show', @adotante %> |
<%= link_to 'Back', adotantes_path %>

app/views/adotantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adotantes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estado</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Pedido oracao</th>
      <th>Marcou comprometimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adotantes.each do |adotante| %>
      <tr>
        <td><%= adotante.nome %></td>
        <td><%= adotante.estado %></td>
        <td><%= adotante.email %></td>
        <td><%= adotante.telefone %></td>
        <td><%= adotante.pedido_oracao %></td>
        <td><%= adotante.marcou_comprometimento %></td>
        <td><%= link_to 'Show', adotante %></td>
        <td><%= link_to 'Edit', edit_adotante_path(adotante) %></td>
        <td><%= link_to 'Destroy', adotante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adotante', new_adotante_path %>

app/views/adotantes/new.html.erb
<h1>New Adotante</h1>

<%= render 'form', adotante: @adotante %>

<%= link_to 'Back', adotantes_path %>

app/views/adotantes/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @adotante.nome %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @adotante.estado %>
</p>

<p>
  <strong>Email:</strong>
  <%= @adotante.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @adotante.telefone %>
</p>

<p>
  <strong>Pedido oracao:</strong>
  <%= @adotante.pedido_oracao %>
</p>

<p>
  <strong>Marcou comprometimento:</strong>
  <%= @adotante.marcou_comprometimento %>
</p>

<%= link_to 'Edit', edit_adotante_path(@adotante) %> |
<%= link_to 'Back', adotantes_path %>