config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :adocaos
  resources :adotantes
  resources :website
  get 'website/adoption'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "website#index"
end

app/models/adocao.rb
class Adocao < ApplicationRecord
  belongs_to :pna
  belongs_to :adotante
end

app/controllers/adocaos_controller.rb
class AdocaosController < ApplicationController
  before_action :set_adocao, only: [:show, :edit, :update, :destroy]

  # GET /adocaos
  # GET /adocaos.json
  def index
    @adocaos = Adocao.all
  end

  # GET /adocaos/1
  # GET /adocaos/1.json
  def show
  end

  # GET /adocaos/new
  def new
    @adocao = Adocao.new
  end

  # GET /adocaos/1/edit
  def edit
  end

  # POST /adocaos
  # POST /adocaos.json
  def create
    @adocao = Adocao.new(adocao_params)

    respond_to do |format|
      if @adocao.save
        format.html { redirect_to @adocao, notice: 'Adocao was successfully created.' }
        format.json { render :show, status: :created, location: @adocao }
      else
        format.html { render :new }
        format.json { render json: @adocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adocaos/1
  # PATCH/PUT /adocaos/1.json
  def update
    respond_to do |format|
      if @adocao.update(adocao_params)
        format.html { redirect_to @adocao, notice: 'Adocao was successfully updated.' }
        format.json { render :show, status: :ok, location: @adocao }
      else
        format.html { render :edit }
        format.json { render json: @adocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adocaos/1
  # DELETE /adocaos/1.json
  def destroy
    @adocao.destroy
    respond_to do |format|
      format.html { redirect_to adocaos_url, notice: 'Adocao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adocao
      @adocao = Adocao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adocao_params
      params.require(:adocao).permit(:pna_id, :adotante_id, :data_adocao)
    end
end

app/helpers/adocaos_helper.rb
module AdocaosHelper
end

app/views/adocaos/_form.html.erb
<%= form_with(model: adocao, local: true) do |form| %>
  <% if adocao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adocao.errors.count, "error") %> prohibited this adocao from being saved:</h2>

      <ul>
        <% adocao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pna_id %>
    <%= form.text_field :pna_id %>
  </div>

  <div class="field">
    <%= form.label :adotante_id %>
    <%= form.text_field :adotante_id %>
  </div>

  <div class="field">
    <%= form.label :data_adocao %>
    <%= form.date_select :data_adocao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adocaos/edit.html.erb
<h1>Editing Adocao</h1>

<%= render 'form', adocao: @adocao %>

<%= link_to 'Show', @adocao %> |
<%= link_to 'Back', adocaos_path %>

app/views/adocaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adocaos</h1>

<table>
  <thead>
    <tr>
      <th>Pna</th>
      <th>Adotante</th>
      <th>Data adocao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adocaos.each do |adocao| %>
      <tr>
        <td><%= adocao.pna_id %></td>
        <td><%= adocao.adotante_id %></td>
        <td><%= adocao.data_adocao %></td>
        <td><%= link_to 'Show', adocao %></td>
        <td><%= link_to 'Edit', edit_adocao_path(adocao) %></td>
        <td><%= link_to 'Destroy', adocao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adocao', new_adocao_path %>

app/views/adocaos/new.html.erb
<h1>New Adocao</h1>

<%= render 'form', adocao: @adocao %>

<%= link_to 'Back', adocaos_path %>

app/views/adocaos/show.html.erb
<p>
  <strong>Pna:</strong>
  <%= @adocao.pna_id %>
</p>

<p>
  <strong>Adotante:</strong>
  <%= @adocao.adotante_id %>
</p>

<p>
  <strong>Data adocao:</strong>
  <%= @adocao.data_adocao %>
</p>

<%= link_to 'Edit', edit_adocao_path(@adocao) %> |
<%= link_to 'Back', adocaos_path %>